[package]
name = "fdl-executor"
description = "FDL (Flow Definition Language) core execution engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fdl-gml = { workspace = true }
fdl-tools = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio-test = { workspace = true }
